# Generated by Django 3.2.5 on 2021-07-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='point',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
