# Generated by Django 3.2.5 on 2021-07-07 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='itemstatus',
            table='item_status',
        ),
        migrations.AlterModelTable(
            name='orderitems',
            table='order_items',
        ),
        migrations.AlterModelTable(
            name='orderstatus',
            table='order_status',
        ),
    ]
