# Generated by Django 3.2.5 on 2021-07-07 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210707_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='option',
            new_name='name',
        ),
    ]
